---
- block:
    - name: Install agent from deb using APT  (when install is needed).
      ansible.builtin.apt:
        deb: "{{ checkmk__register_agent_tempdir.path }}/{{ checkmk__tmp_filename }}"
        state: present
  when: checkmk_agent__register_agent_version_output.stdout != checkmk_agent_version
