---
# tasks file of ansible-role jonaspammer.checkmk_agent

- name: check if all variables have been set correctly
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: Include Tasks for installing the CheckMK Agent by using the system package manager (when install is needed).
  ansible.builtin.include_tasks: "install-{{ ansible_os_family }}.yml"
