---
- name: prepare
  hosts: all,!checkmk-server
  become: true
  gather_facts: false

  roles:
    - role: jonaspammer.bootstrap
    - role: jonaspammer.core_dependencies

# NOTE: only needed for testing!
#       this play is not needed for prepararation of checkmk_agent provisioning :)
- name: prepare checkmk-server
  hosts: checkmk-server
  become: true
  gather_facts: false

  roles:
    - role: jonaspammer.bootstrap
    - role: jonaspammer.core_dependencies
    - role: jonaspammer.checkmk_server
