---
- name: prepare
  hosts: all,!checkmk_server
  become: true
  gather_facts: false

  roles:
    - role: jonaspammer.bootstrap
    - role: jonaspammer.core_dependencies

- name: prepare checkmk_server
  hosts: checkmk_server
  become: true
  gather_facts: false

  roles:
    - role: jonaspammer.bootstrap
    - role: jonaspammer.core_dependencies
    - role: jonaspammer.checkmk_server
