---
- name: output some generally helpful debug information about the provisioned machine
  hosts: all,!checkmk-server
  become: true
  gather_facts: true

  tasks:
    - name: debug output machine facts
      ansible.builtin.include_tasks: ../resources/debug.yml

### Actual Role Verification Tasks:
- name: Verify
  hosts: all,!checkmk-server

  tasks:
    - name: populate service facts
      ansible.builtin.service_facts:

    - name: Execute check_mk_agent.
      ansible.builtin.command: "check_mk_agent"
      changed_when: false
      register: checkmk_agent__register_command

    - name: Assert check_mk_agent output.
      ansible.builtin.assert:
        that:
          - "'<<<check_mk>>>' in checkmk_agent__register_command.stdout"
        quiet: true

    - name: Assert agent service is running.
      ansible.builtin.assert:
        that: "'check_mk-async.service' in ansible_facts.services"
